83 reduce padding and margin for items
heyitscarloc/super-todo-uper pull request #87
Opened 2022-12-06 13:41 UTC by paintvvitch

High chance this is wrong, added row + col in bootstrap. New bug found?

2022-12-06 15:48 UTC, heyitscarloc requested changes
Ur pr title doesn't match the code associated with it???

2022-12-12 16:20 UTC, paintvvitch commented
fixed margin and padding

2022-12-12 17:05 UTC, heyitscarloc requested changes
review comments

2022-12-12 17:26 UTC, heyitscarloc requested changes

2022-12-12 17:26 UTC, heyitscarloc commented on index.html
> -              <div class="float-end">
you want to keep the div class="float-end" here to ensure that the button is set to the far most right

2022-12-12 17:26 UTC, heyitscarloc commented on index.html
> +                <div class="col-sm-11">
in a xs view port the button is still wrapping to a new line. try changing this to col-11 instead of col-sm-11

2022-12-12 17:26 UTC, heyitscarloc commented on index.html
> +                <div class="col-sm-1">
col-1 instead of col-sm-1

2022-12-12 17:44 UTC, heyitscarloc approved these changes
nice

2022-12-12 17:44 UTC, merged